#ifndef __BTSTACK_CONFIG
#define __BTSTACK_CONFIG

// Evita redefiniciones si ya vienen del SDK
#ifndef ENABLE_BLE
#define ENABLE_BLE
#endif

#define ENABLE_LE_PERIPHERAL
#define ENABLE_LE_CENTRAL
#define ENABLE_L2CAP_LE_CREDIT_BASED_FLOW_CONTROL_MODE


// Buffer sizes
#define HCI_OUTGOING_PRE_BUFFER_SIZE 4
#define HCI_ACL_PAYLOAD_SIZE 1021
//#define HCI_EVENT_BUFFER_SIZE 70
#define HCI_ACL_CHUNK_SIZE_ALIGNMENT 4
#define HCI_NUM_ACL_BUFFERS 3
#define MAX_NR_LE_DEVICE_DB_ENTRIES 4

// L2CAP config
#define MAX_NR_L2CAP_SERVICES 3
#define MAX_NR_L2CAP_CHANNELS 3

// ATT + GATT
#define MAX_NR_ATT_SERVERS 1
#define MAX_NR_GATT_CLIENTS 1
#define MAX_NR_HCI_CONNECTIONS 1

// General BTstack features
#define ENABLE_L2CAP_LE_CREDIT_BASED_FLOW_CONTROL_MODE
#define ENABLE_LE_PERIPHERAL
#define ENABLE_LE_CENTRAL
#define ENABLE_LOG_INFO
#define ENABLE_LOG_ERROR
#define ENABLE_PRINTF_HEXDUMP
#define NVM_NUM_DEVICE_DB_ENTRIES 4


#define HAVE_MALLOC

#endif
