# Generated by Django 5.2.7 on 2025-10-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='astroobject',
            name='imageUrl',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/8/8b/Arcturus_star.jpg'),
        ),
        migrations.AddField(
            model_name='astroobject',
            name='info',
            field=models.TextField(default='Sin informacion'),
        ),
    ]
